skins.1=1
name.1=ipattern:*freshwater jellyfish*

skins.2=2
name.2=ipattern:*saltwater jellyfish*

skins.3=2 
biomes.3=cold_ocean deep_cold_ocean frozen_ocean deep_frozen_ocean snowy_beach ocean beach warm_ocean deep_lukewarm_ocean lukewarm_ocean  deep_ocean mushroom_fields stony_shore

skins.4=1