org.gradle.jvmargs=-Xmx8G

#Minecraft Properties
minecraft_version=26.1.2
enabled_platforms=fabric,neoforge

#Mod Properties
modid=conquest
archives_base_name=ConquestReforged-Core
mod_version=BETA-0.0.1
maven_group=com.conquestreforged.core

#Dependencies
architectury_version=20.0.4
fabric_loader_version=0.19.3
fabric_api_version=0.150.0+26.1.2
neoforge_version = 26.1.2.76
modmenu_version = 18.0.0-beta.1
geckolib_version = 5.5.2

